# Generated by Django 5.0.2 on 2024-02-10 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 10, 18, 8, 57, 877783, tzinfo=datetime.timezone.utc)),
        ),
    ]
